import type { Database } from "./types.js";

export function createSeed(): Database {
  return {
    membership: {
      demoDiscountPercent: 10,
      note: "Descuento ficticio de demostración. No representa reglas comerciales reales de Farmaenlace, BYD ni SmartClub.",
    },
    users: [
      {
        id: "user-general",
        name: "Ana Pérez",
        email: "ana.demo@smartclub.test",
        phone: "+593 99 000 0001",
        isMember: false,
        memberTier: null,
        memberSince: null,
        role: "CLIENTE",
        password: "Ana2026!",
        customerCode: "SWC-ANA01",
        virtualCard: "SW-DEMO-0000-0001",
        consentMarketing: false,
        termsAccepted: true,
        dataset: "live",
      },
      {
        id: "user-socio",
        name: "Carlos Mendoza",
        email: "carlos.demo@smartclub.test",
        phone: "+593 99 000 0002",
        isMember: true,
        memberTier: "Socio SmartClub (demo)",
        memberSince: "2024-03-12",
        role: "CLIENTE",
        password: "Carlos2026!",
        customerCode: "SWC-CAR02",
        virtualCard: "SW-DEMO-0000-0002",
        consentMarketing: true,
        termsAccepted: true,
        dataset: "live",
      },
      {
        id: "user-cajero",
        name: "Caja VENDIX Demo",
        email: "cajero@farmaenlace.demo",
        phone: "+593 99 000 0003",
        isMember: false,
        memberTier: null,
        memberSince: null,
        role: "CAJERO_DEMO",
        password: "Caja2026!",
        customerCode: "STAFF-CAJA",
        virtualCard: "SW-DEMO-STAFF-CAJA",
        consentMarketing: false,
        termsAccepted: true,
        dataset: "live",
      },
    ],
    brands: [
      {
        id: "farmacias-economicas",
        name: "Farmacias Económicas",
        shortName: "Farmacias",
        category: "Farmacia",
        color: "#0F766E",
        description: "Catálogo de demostración de medicamentos de venta libre y cuidado personal.",
      },
      {
        id: "medicity",
        name: "Medicity",
        shortName: "Medicity",
        category: "Salud",
        color: "#1D4ED8",
        description: "Catálogo de demostración de dispositivos y cuidado de la salud.",
      },
      {
        id: "wellderma",
        name: "Wellderma",
        shortName: "Wellderma",
        category: "Cuidado personal",
        color: "#BE185D",
        description: "Catálogo de demostración de dermocosmética.",
      },
      {
        id: "ambiente",
        name: "Ambiente",
        shortName: "Ambiente",
        category: "Hogar",
        color: "#B45309",
        description: "Catálogo de demostración de productos para el hogar.",
      },
      {
        id: "mascotas",
        name: "Mascotas",
        shortName: "Mascotas",
        category: "Mascotas",
        color: "#C2410C",
        description: "Catálogo de demostración de alimento y accesorios para mascotas.",
      },
      {
        id: "byd",
        name: "BYD",
        shortName: "BYD",
        category: "Movilidad",
        color: "#334155",
        description: "Accesorios de bajo valor para demostración. No incluye vehículos ni financiación.",
      },
    ],
    products: [
      p("fe-1", "farmacias-economicas", "Paracetamol 500 mg x 20", "Analgésico de demostración", 250, "FE-001"),
      p("fe-2", "farmacias-economicas", "Ibuprofeno 400 mg x 10", "Antiinflamatorio de demostración", 320, "FE-002"),
      p("fe-3", "farmacias-economicas", "Alcohol antiséptico 250 ml", "Antiséptico de demostración", 180, "FE-003"),
      p("fe-4", "farmacias-economicas", "Vitamina C 1 g x 10", "Suplemento de demostración", 450, "FE-004"),
      p("fe-5", "farmacias-economicas", "Gel antibacterial 60 ml", "Higiene de demostración", 200, "FE-005"),
      p("md-1", "medicity", "Tensiómetro digital", "Dispositivo de demostración", 2490, "MD-001"),
      p("md-2", "medicity", "Oxímetro de pulso", "Dispositivo de demostración", 1850, "MD-002"),
      p("md-3", "medicity", "Mascarillas x 10", "Protección de demostración", 390, "MD-003"),
      p("md-4", "medicity", "Termómetro digital", "Dispositivo de demostración", 990, "MD-004"),
      p("md-5", "medicity", "Suero oral", "Hidratación de demostración", 150, "MD-005"),
      p("wd-1", "wellderma", "Crema hidratante 50 ml", "Cuidado facial de demostración", 1200, "WD-001"),
      p("wd-2", "wellderma", "Protector solar FPS 50", "Fotoprotección de demostración", 1550, "WD-002"),
      p("wd-3", "wellderma", "Sérum vitamina C 30 ml", "Tratamiento de demostración", 2200, "WD-003"),
      p("wd-4", "wellderma", "Limpiador facial 150 ml", "Limpieza de demostración", 990, "WD-004"),
      p("am-1", "ambiente", "Ambientador en aerosol", "Hogar de demostración", 450, "AM-001"),
      p("am-2", "ambiente", "Detergente líquido 1 L", "Limpieza de demostración", 680, "AM-002"),
      p("am-3", "ambiente", "Papel higiénico x 4", "Hogar de demostración", 320, "AM-003"),
      p("am-4", "ambiente", "Lavavajillas 500 ml", "Cocina de demostración", 510, "AM-004"),
      p("ms-1", "mascotas", "Alimento para perro 1 kg", "Nutrición de demostración", 890, "MS-001"),
      p("ms-2", "mascotas", "Arena para gato 4 kg", "Higiene de demostración", 650, "MS-002"),
      p("ms-3", "mascotas", "Juguete para mascota", "Accesorio de demostración", 300, "MS-003"),
      p("ms-4", "mascotas", "Shampoo para mascota", "Cuidado de demostración", 720, "MS-004"),
      p("by-1", "byd", "Llavero de demostración", "Accesorio de bajo valor", 400, "BY-001"),
      p("by-2", "byd", "Alfombrilla para taza", "Accesorio de bajo valor", 650, "BY-002"),
      p("by-3", "byd", "Cable USB para auto", "Accesorio de bajo valor", 990, "BY-003"),
      p("by-4", "byd", "Organizador de consola", "Accesorio de bajo valor", 1200, "BY-004"),
      p("by-5", "byd", "Aromatizante para auto", "Accesorio de bajo valor", 350, "BY-005"),
    ],
    orders: [],
    movements: [
      {
        id: "mov-seed-carlos-1",
        userId: "user-socio",
        type: "RECHARGE",
        status: "approved",
        amountCents: 5000,
        signedAmountCents: 5000,
        brandId: null,
        channel: "recharge",
        orderId: null,
        orderReference: null,
        rechargeId: "rec-seed-carlos-1",
        relatedMovementId: null,
        description: "Recarga inicial de demostración",
        receiptCode: "RC-DEMO-5000",
        createdAt: "2026-09-20T14:00:00.000Z",
        postedAt: "2026-09-20T14:00:02.000Z",
      },
    ],
    recharges: [
      {
        id: "rec-seed-carlos-1",
        userId: "user-socio",
        amountCents: 5000,
        status: "approved",
        processorRef: "PAYMOCK-SEED-001",
        movementId: "mov-seed-carlos-1",
        createdAt: "2026-09-20T14:00:00.000Z",
        settledAt: "2026-09-20T14:00:02.000Z",
        origin: "APP",
        tender: "processor_sim",
        cashierId: null,
      },
    ],
    usedIdempotencyKeys: {},
    sessions: [],
    flowEvents: [],
  };
}

function p(
  id: string,
  brandId: Database["products"][number]["brandId"],
  name: string,
  description: string,
  priceCents: number,
  sku: string,
) {
  return { id, brandId, name, description, priceCents, sku };
}
